#!/bin/sh
echo "Building optimized Brunch application"
cd source
brunch build --optimize
cd ..
echo "Moving contents to project root"
mv -f source/public/* .
echo "Committing optimized files"
git add index.html
git add images
git add scripts
git add styles