#!/bin/sh
echo "Building optimized Brunch application"
cd source
brunch build --optimize
cd ..
echo "Copying contents to project root"
cp -r source/public/* .
echo "Committing optimized files"
git add index.html images scripts styles